name: qiscus_multichannel_widget
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.2
  date_format: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  grouped_list: ^4.2.0
  http: ^0.13.4
  qiscus_chat_sdk: ^2.0.0-beta.1
  flutter_riverpod: ^2.0.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7

flutter:
  assets:
    - lib/src/assets/
