name: qiscus_multichannel_widget
description: Omnichannel Platform to Increase Sales and Customer Loyalty.
version: 1.0.0-beta.2
homepage: https://www.qiscus.com/en

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  qiscus_chat_sdk: ^2.0.0-beta.3
  freezed_annotation: ^2.0.3
  grouped_list: ^5.1.1
  http: ^0.13.4
  flutter_riverpod: ^2.0.0-dev.9
  date_format: ^2.0.5
  open_file: ^3.2.1
  url_launcher: ^6.1.0
  file_picker: ^4.6.1
  json_annotation: ^4.5.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^2.0.3
  json_serializable: ^6.1.6
  build_runner: ^2.1.7

# dependency_overrides:
#   qiscus_chat_sdk:
#     path: ../qiscus-chat-sdk-flutter

flutter:
  assets:
    - lib/src/assets/
